language: java
dist: bionic
jdk: openjdk11
env:
  global:
    - PYENV_VERSION=3.7
    - AWS_REGION="us-east-1"
    - AWS_DEFAULT_REGION=$AWS_REGION
install:
  - pip3 install --user pre-commit cloudformation-cli-java-plugin
before_script:
  - pre-commit run --all-files --verbose
jobs:
  include:
    - script: |
        for directory in $TRAVIS_BUILD_DIR/aws-*; do
          cd "$directory"
          mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B clean verify || travis_terminate 1
        done
