version: 0.2
phases:
  install:
    runtime-versions:
        java: openjdk8
        python: 3.7
    commands:
      # make sure pip/setuptools/wheel is up to date, awscli for SDK patching
      - cd "$CODEBUILD_SRC_DIR_JAVA_PLUGIN"
      - pip install --upgrade pip setuptools wheel awscli -r "$CODEBUILD_SRC_DIR_RPDK/requirements.txt"
      - mkdir "$CODEBUILD_SRC_DIR_JAVA_PLUGIN/artifacts"
  build:
    commands:
      # pre-build check for commit hooks
      - cd "$CODEBUILD_SRC_DIR"
      - pre-commit run --all-files
      # install aws-cloudformation-resource-schema
      - cd "$CODEBUILD_SRC_DIR_SCHEMA"
      - >
        mvn package org.apache.maven.plugins:maven-install-plugin:3.0.0-M1:install
        --batch-mode
        --no-transfer-progress
      # install internal SDK
      - >
        mvn org.apache.maven.plugins:maven-install-plugin:3.0.0-M1:install-file
        --batch-mode
        --no-transfer-progress
        -Dfile="$CODEBUILD_SRC_DIR_SDK/cloudformation-2.8.1.jar"
      # install aws-cloudformation-rpdk
      - cd "$CODEBUILD_SRC_DIR_JAVA_PLUGIN"
      - >
        mvn package org.apache.maven.plugins:maven-install-plugin:3.0.0-M1:install
        --batch-mode
        --no-transfer-progress
      - pip install "$CODEBUILD_SRC_DIR_RPDK" .
      # end-to-end test child repo(s)
      - cd "$CODEBUILD_SRC_DIR"
      - cd aws-logs-loggroup
      - mvn clean verify --no-transfer-progress
    finally:
      - cat "$CODEBUILD_SRC_DIR/aws-logs-loggroup/rpdk.log"
