AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the AWS::Logs::LogStream resource type

Globals:
  Function:
    Timeout: 180  # docker start-up times can be long for SAM CLI
    MemorySize: 1024

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: software.amazon.logs.logstream.HandlerWrapper::handleRequest
      Runtime: java8
      CodeUri: ./target/aws-logs-logstream-handler-1.0-SNAPSHOT.jar

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: software.amazon.logs.logstream.HandlerWrapper::testEntrypoint
      Runtime: java8
      CodeUri: ./target/aws-logs-logstream-handler-1.0-SNAPSHOT.jar

